export const metadata = {
  title: "Terms of Service | Meraki Estimator",
};

export default function TermsPage() {
  return (
    <main style={{ maxWidth: 860, margin: "0 auto", padding: "40px 20px", lineHeight: 1.65 }}>
      <h1>Terms of Service</h1>
      <p><strong>Last updated:</strong> 2026-01-02</p>

      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of Meraki Estimator (the &quot;Service&quot;) provided
        by Meraki Home &amp; Build (&quot;we&quot;, &quot;us&quot;). By using the Service, you agree to these Terms.
      </p>

      <h2>1. Eligibility</h2>
      <p>You must be able to form a binding contract and comply with applicable laws.</p>

      <h2>2. Accounts and authentication</h2>
      <p>
        You are responsible for safeguarding your account and for activities under your account. If you use Google sign-in,
        authentication is handled through Google and our authentication provider.
      </p>

      <h2>3. Use of the Service</h2>
      <ul>
        <li>You will use the Service only for lawful purposes.</li>
        <li>You will not attempt to disrupt, reverse engineer, or misuse the Service.</li>
        <li>You are responsible for the accuracy of information you submit.</li>
      </ul>

      <h2>4. Estimates and disclaimers</h2>
      <p>
        Estimates generated by the Service are informational and may vary based on site conditions, scope changes, supplier
        pricing, and other factors. We do not guarantee specific outcomes.
      </p>

      <h2>5. Intellectual property</h2>
      <p>
        We retain all rights in the Service, including software, design, and content. You retain rights to your own inputs.
      </p>

      <h2>6. Termination</h2>
      <p>
        We may suspend or terminate access if you violate these Terms or if necessary for security or legal reasons. You may
        stop using the Service at any time.
      </p>

      <h2>7. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, we are not liable for indirect, incidental, or consequential damages, or for
        loss of profits, data, or goodwill arising from use of the Service.
      </p>

      <h2>8. Changes</h2>
      <p>
        We may update these Terms from time to time. Continued use after changes means you accept the updated Terms.
      </p>

      <h2>9. Contact</h2>
      <p>
        Questions: <a href="mailto:manager@merakihomeandbuild.com">manager@merakihomeandbuild.com</a>
      </p>
      <p>Company: Meraki Home &amp; Build</p>
    </main>
  );
}
